# Generated by Django 4.0 on 2022-06-07 14:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('survey', '0002_alter_surveyquestion_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('week', models.ForeignKey(db_column='week_number', default=1, on_delete=django.db.models.deletion.CASCADE, to='survey.week')),
            ],
        ),
    ]
